repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
        -   id: check-yaml
            language: system
        -   id: end-of-file-fixer
            language: system
        -   id: trailing-whitespace
            language: system
        -   id: check-added-large-files
            language: system
            args: ['--maxkb=1000']

-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
        -   id: black
            language: system

# NOTE: Django templates are not strictly HTML files, and are therefore
# tricky to format in a clean and consistent way. djlint will attempt to
# reformat and check for compliance with HTML/Django template best practices
# (see more about formatting and linting in the documentation here
# https://www.djlint.com/docs/configuration/). djlint can be configured to desired
# specifications using the .djlintrc file.
-   repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.19.16
    hooks:
        -   id: djlint-django
            entry: djlint --profile=django --reformat --lint

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.0
    hooks:
        -   id: prettier
            types_or: [css, javascript]
